# fly.toml app configuration file generated for ncdatingapp on 2023-07-13T10:23:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ncdatingapp"
primary_region = "ams"

[build]
  image = "kovad003/ncdatingapp:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
